"use client";
import Nav from '@/lib/components/Nav'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/lib/components/Footer'
import { AuthProvider } from '@/lib/context/AuthProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <AuthProvider>
        <Nav></Nav>
        {children}
        <Footer></Footer>
        </AuthProvider>
        </body>
    </html>
  )
}
